import { ProjectItem, CertificationItem, EducationItem, AchievementItem, SkillCategory } from './types';

export const PERSONAL_INFO = {
  name: 'Padmaroopa D.',
  title: 'Web Developer | Python Enthusiast | UI/UX Designer',
  badgeText: 'Final Year B.Tech ISE Student',
  subheading: 'Info Science · Dev · UI/UX',
  bio: 'A passionate final-year Information Science and Engineering student dedicated to crafting responsive, high-performance web applications, intelligent ML workflows, and human-centric user experiences.',
  aboutLong1: 'I am a final-year Information Science and Engineering student passionate about crafting reliable, scalable web applications, exploring intelligent Python & machine learning models, and designing intuitive, human-centric user experiences.',
  aboutLong2: 'With a strong analytical mindset and real-world internship exposure at Aquila Innovations and Alfrin Technologies, I enjoy taking concepts from algorithmic thinking and database architecture all the way through to refined, accessible interfaces.',
  careerObjective: 'Dedicated to building practical, scalable software solutions and continuously growing as a software engineer in high-impact, collaborative environments where innovation, clean code, and continuous learning thrive.',
  cgpa: '7.25',
  cgpaFull: '7.25 / 10.0',
  internshipsCount: '2x',
  credentialsCount: '7+',
  handle: '@padmarupa31',
  email: 'padmaroopa123@gmail.com',
  githubUrl: 'https://github.com/padmarupa31',
  linkedinUrl: 'https://www.linkedin.com/in/padmaroopa-d-097011433/',
  availableStatus: 'Available for Opportunities',
  batchPeriod: '2025/2026',
};

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    title: 'Programming',
    label: 'Languages',
    description: 'Object-oriented programming, data structures, and algorithmic logic.',
    icon: 'terminal',
    skills: ['Python', 'C', 'Java', 'JavaScript'],
    footerText: 'OOP · Algorithms',
    footerIcon: 'code',
    accent: 'primary',
  },
  {
    title: 'Web Development',
    label: 'Full Stack',
    description: 'Building responsive frontends and lightweight, performant REST APIs.',
    icon: 'language',
    skills: ['HTML5', 'CSS3', 'Flask', 'Node.js', 'Express.js'],
    footerText: 'Responsive · REST APIs',
    footerIcon: 'api',
    accent: 'secondary',
  },
  {
    title: 'Machine Learning & Data',
    label: 'Intelligent Systems',
    description: 'Applied statistical modeling, text vectorization, and similarity analysis.',
    icon: 'neurology',
    skills: ['Scikit-learn', 'Machine Learning', 'NLP', 'TF-IDF', 'Cosine Similarity'],
    footerText: 'Vector Modeling · NLP',
    footerIcon: 'model_training',
    accent: 'tertiary',
  },
  {
    title: 'Databases',
    label: 'Data Architecture',
    description: 'Relational schema design, querying, indexing, and data integrity.',
    icon: 'database',
    skills: ['MySQL', 'SQL', 'Relational Schemas', 'Query Optimization'],
    footerText: 'CRUD · Normalization',
    footerIcon: 'table_chart',
    accent: 'primary',
  },
  {
    title: 'UI/UX Design',
    label: 'Product & Visual',
    description: 'User journeys, design system tokens, and accessible visual interfaces.',
    icon: 'palette',
    skills: ['Figma', 'UI/UX Design', 'Wireframing', 'Prototyping'],
    footerText: 'Design Tokens · WCAG',
    footerIcon: 'brush',
    accent: 'secondary',
  },
  {
    title: 'Development Tools',
    label: 'Workflow & Env',
    description: 'Version control, collaborative workflows, and integrated development environments.',
    icon: 'construction',
    skills: ['Git', 'GitHub', 'VS Code', 'PyCharm', 'Jupyter Notebook', 'XAMPP'],
    footerText: 'CI/CD · Version Control',
    footerIcon: 'build_circle',
    accent: 'tertiary',
  },
];

export const PROJECTS: ProjectItem[] = [
  {
    id: 'project-1',
    projectNumber: 'PROJECT 01',
    category: 'Machine Learning / NLP',
    statusText: 'Production Ready',
    statusType: 'production',
    title: 'Plagiarism Key Detection',
    description:
      'A plagiarism detection system that analyzes and compares documents using TF-IDF and Cosine Similarity. It calculates similarity percentages and classifies documents into plagiarism levels.',
    features: [
      'Vectorized text comparison using TF-IDF',
      'Cosine similarity metric score calculation',
      'Real-time document similarity percentage',
      'Multi-level plagiarism severity classification (Low / Moderate / High)',
      'Clean web interface for batch text & file analysis',
    ],
    techStack: ['Python', 'Flask', 'Scikit-learn', 'Pandas', 'TF-IDF', 'Cosine Similarity', 'HTML', 'CSS'],
    repoLink: 'https://github.com/padmarupa31/plagiarism_key_detection',
    viewLink: 'https://github.com/padmarupa31/plagiarism_key_detection',
    liveUrl: 'https://plagiarism-key-detection-7.onrender.com',
  },
  {
    id: 'project-2',
    projectNumber: 'PROJECT 02',
    category: 'Mobile Product Design / UI/UX',
    statusText: 'Interactive Prototype',
    statusType: 'prototype',
    title: 'Bloomora – Flower Shop E-Commerce Application',
    description:
      'A mobile e-commerce application for a flower shop where users can browse bouquets, indoor plants and gift products. Includes product categories, search, cart and checkout flows.',
    features: [
      'Human-centered mobile user journey & wireframes',
      'Interactive product catalog (bouquets, plants, gifts)',
      'Instant search, category filters & order summary',
      'Complete end-to-end checkout & payment flow',
      'Design system with typography, soft floral accents & 8pt grid',
    ],
    techStack: ['Figma', 'UI/UX Design', 'Prototyping', 'Design Systems', 'User Flows', 'Wireframing'],
    viewLink:
      'https://www.figma.com/design/s7JtxmFFRGXmcDKbyx9kol/2303121026_Padmaroopa_UIUX_Assignment1?node-id=3-6&t=EyEyNLf8Sug7Fgok-1',
    liveUrl:
      'https://www.figma.com/proto/s7JtxmFFRGXmcDKbyx9kol/2303121026_Padmaroopa_UIUX_Assignment1?node-id=341-247&p=f&t=ze3Qm0kxCFKigVIw-1&scaling=scale-down&content-scaling=fixed&page-id=3%3A7',
  },
  {
    id: 'project-3',
    projectNumber: 'PROJECT 03',
    category: 'Full-Stack Web / Database',
    statusText: 'Role Auth & MySQL',
    statusType: 'live',
    title: 'Blog Management System',
    description:
      'A full-stack blogging platform where users can register, log in, create, edit, delete, and manage their own blog posts. Includes MySQL database integration, authentication, session management, and author-based post ownership.',
    features: [
      'User authentication & session management',
      'Author-based post ownership and access control',
      'Create, edit, delete, and view blog posts',
      'MySQL database integration',
      'Responsive web interface',
    ],
    techStack: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'Express.js', 'MySQL'],
    repoLink: 'https://github.com/padmarupa31/blog_management_system',
    viewLink: 'https://github.com/padmarupa31/blog_management_system',
    liveUrl: 'https://blog-management-system-16y8.onrender.com/',
  },
];

export const EDUCATION_DATA: EducationItem[] = [
  {
    period: '2021 – 2025 / 2026',
    statusBadge: 'Current · Final Year',
    scoreText: 'CGPA: 7.25 / 10.0',
    scoreIcon: 'grade',
    degree: 'Bachelor of Technology (B.Tech)',
    field: 'Information Science and Engineering (ISE)',
    coursework: [
      'Data Structures & Algorithms',
      'Database Management Systems',
      'Machine Learning',
      'Web Technologies',
      'Software Engineering',
    ],
    colorVariant: 'primary',
  },
  {
    period: 'Completed 2023',
    statusBadge: 'Pre-University / 12th',
    scoreText: 'Score: 76.0%',
    scoreIcon: 'analytics',
    degree: 'Higher Secondary (12th Grade)',
    field: 'Science Stream: Physics, Chemistry, Mathematics & Computer Science (PCMC)',
    colorVariant: 'secondary',
  },
  {
    period: 'Completed 2021',
    statusBadge: 'Secondary / 10th',
    scoreText: 'Distinction Foundation',
    scoreIcon: 'verified',
    degree: 'Secondary School Leaving Certificate (10th)',
    field: 'Secondary Education with strong quantitative grasp across Mathematics and Natural Sciences.',
    colorVariant: 'tertiary',
  },
];

export const CERTIFICATIONS: CertificationItem[] = [
  {
    id: 'cert-aquila',
    issuer: 'Aquila Innovations',
    title: 'Python Programming Internship',
    description: '30-Day Intensive Internship Program: Python OOP, functions, file handling, and algorithmic problem solving.',
    badge: 'Completed',
    durationOrYear: '14 June 2025 – 15 July 2025',
    verifiedLabel: 'Official PDF',
    icon: 'terminal',
    variant: 'primary',
    fileType: 'pdf',
    fileUrl: '/certificates/aquila_innovations_python_internship_certificate.pdf',
    previewImageUrl: '/certificates/aquila_innovations_python_internship_certificate.jpg',
    downloadName: 'Padmaroopa_D_Aquila_Innovations_Python_Internship_Certificate.pdf',
    certificateTitle: 'Internship Completion Certificate',
    recipientName: 'Ms. D. Padmaroopa',
    courseOrAchievement: '30-Day Intensive Internship Program in Python Programming',
    issueDate: '14 June 2025 – 15 July 2025',
    certificateId: 'AQ-INTERN-2025-0715',
    gradeOrDistinction: 'Excellent Evaluation · Problem Solving & Python',
    signatoryName: 'Aswin Sadhasivam',
    signatoryTitle: 'CTO – Aquila Innovations',
    signatoryRole: 'MCP, SOTY - Canada, CPPG - CANADA, Honors - U.K',
    skills: ['Python Programming', 'Practical Python', 'Problem Solving', 'OOP', 'File Handling'],
    credentialUrl: '/certificates/aquila_innovations_python_internship_certificate.pdf',
  },
  {
    id: 'cert-alfrin',
    issuer: 'Alfrin Technologies',
    title: 'Full Stack Internship',
    description: '15-Day offline intensive program covering practical sessions, live projects, and full stack web architecture.',
    badge: 'Completed',
    durationOrYear: '15.06.2026 – 01.07.2026',
    verifiedLabel: '',
    icon: 'layers',
    variant: 'secondary',
    fileType: 'image',
    fileUrl: '/certificates/certificate3.jpg.jpeg',
    downloadName: 'Padmaroopa_D_Alfrin_Technologies_Full_Stack_Internship.jpg',
    certificateTitle: 'Certificate of Completion',
    recipientName: 'D. PADMAROOPA',
    courseOrAchievement: 'FULL STACK Professional Internship',
    issueDate: '01.07.2026',
    certificateId: 'IN-18-2026',
    gradeOrDistinction: 'Completed (Offline Mode) · 15-DAYS',
    signatoryName: 'Authorized Signatory',
    signatoryTitle: 'Technical Director',
    signatoryRole: 'Alfrin Technologies, Pondicherry',
    skills: ['Full Stack', 'Practical Sessions', 'Live Projects', 'Web Architecture'],
    credentialUrl: '/certificates/certificate3.jpg.jpeg',
  },
  {
    id: 'cert-nptel',
    issuer: 'NPTEL · Swayam · IIT Kanpur',
    title: 'Developing Soft Skills & Personality',
    description: 'Elite NPTEL Certification funded by MoE, Govt. of India with an 86% consolidated score across 12,536 candidates.',
    badge: 'Elite Grade · 86%',
    durationOrYear: 'Aug-Oct 2025 (8 Weeks)',
    verifiedLabel: 'Official PDF',
    icon: 'psychology_alt',
    variant: 'tertiary',
    fileType: 'pdf',
    fileUrl: '/certificates/nptel_developing_soft_skills_and_personality_elite_certificate.pdf',
    previewImageUrl: '/certificates/nptel_developing_soft_skills_and_personality_elite_certificate.jpg',
    downloadName: 'Padmaroopa_D_NPTEL_Elite_Developing_Soft_Skills_and_Personality.pdf',
    certificateTitle: 'NPTEL ONLINE CERTIFICATION',
    recipientName: 'PADMAROOPA D',
    courseOrAchievement: 'Developing Soft Skills and Personality',
    issueDate: 'Aug-Oct 2025',
    certificateId: 'NPTEL25HS174S566700497',
    gradeOrDistinction: 'Elite Grade · Consolidated Score: 86% (Assignments: 24.54/25, Exam: 61.46/75)',
    signatoryName: 'Prof. B. V. Ratish Kumar & Prof. Satyaki Roy',
    signatoryTitle: 'CCE Chairman & NPTEL Coordinator',
    signatoryRole: 'Indian Institute of Technology Kanpur (IIT Kanpur)',
    skills: ['Communication', 'Personality Development', 'Leadership', 'Emotional Intelligence'],
    credentialUrl: '/certificates/nptel_developing_soft_skills_and_personality_elite_certificate.pdf',
  },
  {
    id: 'cert-udemy-ml',
    issuer: 'Udemy',
    title: 'Hands-On Python Machine Learning',
    description: 'Hands-On Python Machine Learning with Real World Projects by Sayman Creative Institute.',
    badge: 'Verified Credential',
    durationOrYear: '4.5 Total Hours',
    verifiedLabel: '',
    icon: 'smart_toy',
    variant: 'tertiary',
    fileType: 'image',
    fileUrl: '/certificates/certificate4.jpg.jpeg',
    downloadName: 'Padmaroopa_Udemy_Hands_On_Python_Machine_Learning.jpg',
    certificateTitle: 'CERTIFICATE OF COMPLETION',
    recipientName: 'Padmaroopa',
    courseOrAchievement: 'Hands-On Python Machine Learning with Real World Projects',
    issueDate: 'Sept. 8, 2026',
    certificateId: 'UC-66589a13-11e5-4b21-8a47-db9020d944e4',
    gradeOrDistinction: 'Reference Number: 0004 · 4.5 total hours',
    signatoryName: 'Sayman Creative Institute',
    signatoryTitle: 'Instructor',
    signatoryRole: 'Udemy Global Learning Network',
    skills: ['Python', 'Machine Learning', 'Data Modeling', 'Real-World Projects'],
    credentialUrl: 'https://ude.my/UC-66589a13-11e5-4b21-8a47-db9020d944e4',
  },
  {
    id: 'cert-udemy-bootcamp',
    issuer: 'Udemy',
    title: 'CS MetaBootcamp 2026',
    description: 'Computer Science MetaBootcamp: Beginner to Intermediate 2026 by Odysy Academy.',
    badge: 'Verified Credential',
    durationOrYear: '7 Total Hours',
    verifiedLabel: '',
    icon: 'computer',
    variant: 'secondary',
    fileType: 'image',
    fileUrl: '/certificates/certificate5.jpg.jpeg',
    downloadName: 'Padmaroopa_Udemy_Computer_Science_MetaBootcamp.jpg',
    certificateTitle: 'CERTIFICATE OF COMPLETION',
    recipientName: 'Padmaroopa',
    courseOrAchievement: 'Computer Science MetaBootcamp: Beginner to Intermediate 2026',
    issueDate: 'Sept. 1, 2026',
    certificateId: 'UC-21538b3e-167b-496a-be87-7cd09067b48a',
    gradeOrDistinction: 'Reference Number: 0004 · 7 total hours',
    signatoryName: 'Odysy Academy',
    signatoryTitle: 'Instructor',
    signatoryRole: 'Udemy Global Learning Network',
    skills: ['Computer Science', 'Data Structures', 'Algorithms', 'Web Architecture'],
    credentialUrl: 'https://ude.my/UC-21538b3e-167b-496a-be87-7cd09067b48a',
  },
  {
    id: 'cert-udemy-design',
    issuer: 'Udemy',
    title: 'Designing Logo, Vector Arts, Icons & QR with AI',
    description: 'Designing Logo, Vector Arts, Icons, Packaging & QR with AI by Christ Raharja.',
    badge: 'Verified Credential',
    durationOrYear: '2.5 Total Hours',
    verifiedLabel: '',
    icon: 'draw',
    variant: 'primary',
    fileType: 'image',
    fileUrl: '/certificates/certificate6.jpg.jpeg',
    downloadName: 'Padmaroopa_Udemy_Designing_Logo_Vector_Arts_AI.jpg',
    certificateTitle: 'CERTIFICATE OF COMPLETION',
    recipientName: 'Padmaroopa',
    courseOrAchievement: 'Designing Logo, Vector Arts, Icons, Packaging & QR with AI',
    issueDate: 'Sept. 1, 2026',
    certificateId: 'UC-18458e62-987a-491f-9a5f-1053e0962f12',
    gradeOrDistinction: 'Reference Number: 0004 · 2.5 total hours',
    signatoryName: 'Christ Raharja',
    signatoryTitle: 'Instructor',
    signatoryRole: 'Udemy Design & AI Academy',
    skills: ['Logo Design', 'Vector Arts', 'Iconography', 'Packaging', 'AI Asset Generation'],
    credentialUrl: 'https://ude.my/UC-18458e62-987a-491f-9a5f-1053e0962f12',
  },
  {
    id: 'cert-udemy-pdf',
    issuer: 'Udemy',
    title: 'Python Project: Build a PDF File Handling Tool',
    description: 'Python Project: Build a PDF File Handling Tool from Scratch by Dr. Raj Gaurav Mishra.',
    badge: 'Verified Credential',
    durationOrYear: '1 Total Hour',
    verifiedLabel: '',
    icon: 'picture_as_pdf',
    variant: 'primary',
    fileType: 'image',
    fileUrl: '/certificates/certificate7.jpg.jpeg',
    downloadName: 'Padmaroopa_Udemy_Python_PDF_File_Handling_Tool.jpg',
    certificateTitle: 'CERTIFICATE OF COMPLETION',
    recipientName: 'Padmaroopa',
    courseOrAchievement: 'Python Project: Build a PDF File Handling Tool from Scratch',
    issueDate: 'Feb. 21, 2025',
    certificateId: 'UC-f9713cff-e2b4-4fdb-8f89-e3395ac3c2de',
    gradeOrDistinction: 'Reference Number: 0004 · 1 total hour',
    signatoryName: 'Dr. Raj Gaurav Mishra',
    signatoryTitle: 'Instructor',
    signatoryRole: 'Udemy Global Learning Network',
    skills: ['Python', 'PDF Handling', 'File Automation', 'Tooling'],
    credentialUrl: 'https://ude.my/UC-f9713cff-e2b4-4fdb-8f89-e3395ac3c2de',
  },
];

export const ACHIEVEMENTS: AchievementItem[] = [
  {
    tag: 'Dual Internship Selection',
    title: 'Selected for Two Competitive Technical Internships',
    description:
      'Successfully qualified and contributed as a Software & Full Stack Intern at both Aquila Innovations and Alfrin Technologies during undergraduate coursework, delivering modular backend code and user interfaces.',
    icon: 'workspace_premium',
    colorVariant: 'primary',
  },
  {
    tag: 'Machine Learning Innovation',
    title: 'End-to-End NLP Plagiarism Engine',
    description:
      'Engineered a practical vectorized text comparison engine utilizing TF-IDF and Cosine Similarity, achieving high accuracy in scoring plagiarism percentages across multi-page technical submissions.',
    icon: 'insights',
    colorVariant: 'secondary',
  },
  {
    tag: 'Design-to-Code Synthesis',
    title: 'Full Fidelity Prototyping in Figma',
    description:
      'Designed comprehensive user experience wireframes and dynamic UI component tokens for multiple applications (including Bloomora), seamlessly translating visual mockups into accessible code.',
    icon: 'auto_fix_high',
    colorVariant: 'tertiary',
  },
  {
    tag: 'Continuous Upskilling',
    title: '7+ Certified Credentials Completed',
    description:
      'Maintained an active personal curriculum alongside B.Tech coursework, securing honors from NPTEL, Udemy, and startup programs spanning machine learning, algorithms, and design systems.',
    icon: 'military_tech',
    colorVariant: 'primary-dim',
  },
];
